config = {
"Vm username": "Sherlock",
"vm pwd":"**",
"Cognitive Services API Url": "https://****.cognitiveservices.azure.com/",
"Cognitive Services API key": "***",
"LUIS API Endpoint":"",
"LUIS API Key":"",
"LUIS API App ID":"",
"Bot App Name":"",
"Bot App ID":"",
"Bot App Password":"",
"Azure Storage name": "***",
"Azure Storage Connection String":"********",
"Azure Storage Key": "***",
"Cosmos DB name": "***",
"Cosmos DB Url": "https://***.documents.azure.com:443/",
"Cosmos DB Key": "****",
"DirectLine Key":"",
}
