config = {
"Vm username": "Sherlock",
"vm pwd":"Sherlock@123",
"Cognitive Services API Url": "https://sherlockcog.cognitiveservices.azure.com/",
"Cognitive Services API key": "f5384588126f43cd9c4d1206dd08c001",
"LUIS API Endpoint":"",
"LUIS API Key":"",
"LUIS API App ID":"",
"Bot App Name":"",
"Bot App ID":"",
"Bot App Password":"",
"Azure Storage name": "sherlockstores",
"Azure Storage Connection String":"DefaultEndpointsProtocol=https;AccountName=sherlockstores;AccountKey=hdaBIgi06JtfGjjtKzF6W61eI/8C8/1Gixow2JlKrgX4DHVsjm+8tPCE9TMF0+KUuPUQhC5LXYUfr+rSRRFdgg==;EndpointSuffix=core.windows.net",
"Azure Storage Key": "hdaBIgi06JtfGjjtKzF6W61eI/8C8/1Gixow2JlKrgX4DHVsjm+8tPCE9TMF0+KUuPUQhC5LXYUfr+rSRRFdgg==",
"Cosmos DB name": "sherlockcosmos",
"Cosmos DB Url": "https://sherlockcosmos.documents.azure.com:443/",
"Cosmos DB Key": "UHwN65FS9OX5lZl1UYc4IVrpoLBUOg0v74aGOT1X18a4fiLEBYOQ0LJSjBFhphNj7Aft8p5R7rDDHMcfSSr2Fg==",
"DirectLine Key":"",
}